server:
  port: 6801

spring:
  application:
    name: order-service
  #################################redis配置########################################
  redis:
    host: 192.168.1.26
    password: kdniao2017
    port: 6389
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
# （普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
#spring.redis.cluster.max-redirects=
# （普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
#spring.redis.cluster.nodes=127.0.0.1:1001,127.0.0.1:1002        

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC连接Mysql6以上com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.233:3306/ordercenter?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sql@kdn!123
    hikari:
      minimum-idle: 5 ## 最小空闲连接数量
      idle-timeout: 180000 ## 空闲连接存活最大时间，默认600000（10分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      auto-commit: true ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      maxLifetime: 600000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    
# ===================================================================
# mybatis配置
# ===================================================================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kj.order

# ===================================================================
# 日志配置
# ===================================================================      
logging: 
  config: classpath:cust-logback.xml
  path: /opt/logs

# ===================================================================
# 服务发现
# ===================================================================    
eureka: 
  instance: 
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 15  #超时时间,默认为90秒,该值至少应该大于leaseRenewalIntervalInSeconds
    lease-renewal-interval-in-seconds: 5      #eureka client发送心跳给server端的频率,默认30秒
  client: 
    register-with-eureka: true
    registryFetchIntervalSeconds: 5       #取服务注册信息间隔，默认为30秒
    #指定服务注册中心的地址,高可用集群时指向其他的eureka服务相互注册，多个用","分割
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      
      
#开启Hystrix
feign:
  hystrix:
    enabled: true

#ribbon全局配置(RibbonRoutingFilter时生效)
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#Hystrix启用超时时间
hystrix: 
  command: 
    default: 
      execution: 
        timeout: 
          enabled: true
        #Hystrix断路器的超时时间，默认是1s，断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000