server:
  port: 6801

spring:
  application:
    name: order-service
  #################################redis配置########################################
  redis:
    host: 127.0.0.1
    #password: 123
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
# （普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
#spring.redis.cluster.max-redirects=
# （普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
#spring.redis.cluster.nodes=127.0.0.1:1001,127.0.0.1:1002        
# ===================================================================
# 日志配置
# ===================================================================      
logging: 
  config: classpath:cust-logback.xml
  path: /opt/logs

# ===================================================================
# 服务发现
# ===================================================================    
eureka: 
  instance: 
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 15  #超时时间,默认为90秒,该值至少应该大于leaseRenewalIntervalInSeconds
    lease-renewal-interval-in-seconds: 5      #eureka client发送心跳给server端的频率,默认30秒
  client: 
    register-with-eureka: true
    registryFetchIntervalSeconds: 5       #取服务注册信息间隔，默认为30秒
    #指定服务注册中心的地址,高可用集群时指向其他的eureka服务相互注册，多个用","分割
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/