server:
  port: 8761
 
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #超时时间,默认为90秒,该值至少应该大于leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 30 
    #eureka client发送心跳给server端的频率,默认30秒
    lease-renewal-interval-in-seconds: 10
  server:       #EurekaServerConfigBean
    #自我保护
    enable-self-preservation: true
    # 清理间隔(单位毫秒，默认是60*1000)
    eviction-interval-timer-in-ms: 1000
  client:
    registerWithEureka: false 
    fetchRegistry: false
    #取服务注册信息间隔，默认为30秒
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
 
spring:
  application:
    name: eurka-server
    
# ===================================================================
# 日志配置
# ===================================================================      
logging: 
  config: classpath:cust-logback.xml
  path: /opt/logs